version: "3.9"

services:
  bank-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank-analyzer:latest
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    # volumes:
      # - "C:/My/BankStatements:/persistence" <- Your bank statement pdfs are stored here
      # - "C:/My/Processed/Data:/resources" <- All processed data is saved here
